# Generated by Django 3.2 on 2021-04-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gin',
            old_name='category',
            new_name='gincategory',
        ),
    ]
