# Generated by Django 3.2 on 2021-04-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0002_rename_category_gin_gincategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gincategory',
            options={'verbose_name_plural': 'Gin Categories'},
        ),
    ]
