# Generated by Django 3.2 on 2021-04-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210430_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user_profile',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_user_profile',
            new_name='post_author',
        ),
    ]
